### ISSUE TITLE
Error with alpha version 0.2

### ISSUE THREAD

**Issue by gabrielacosta** [Superalgos/DesktopApp#76]
Hi, 
I was trying to test the latest release of the desktop application. I run into this error when the application start running on Chrome. 

![image](https://user-images.githubusercontent.com/8519425/67134738-6dd4fa80-f25f-11e9-923b-91780a575214.png)

Could you please help me. 

![image](https://user-images.githubusercontent.com/8519425/67134845-fb184f00-f25f-11e9-8494-64c534951904.png)

Also, I'm a developer. So, I want to be able to fully compile the entire project with all the required repositories. 

I searched the github account for the multiple project that conform the main development. 

![image](https://user-images.githubusercontent.com/8519425/67134759-a70d6a80-f25f-11e9-99d3-6108e48b072e.png)

Could you please provide the order of compilation and the repositories required. 

I could not find any information about, how the desktop build was setup. 

Maybe, later if I can build the application I will join the development team. 

Kind regards, 

Gabriel

P.S: I'm running the version 

![image](https://user-images.githubusercontent.com/8519425/67134860-11bea600-f260-11e9-9dc6-3457592ac6e8.png)

of Chrome with Windows 10 latest build.

**Comment by Luis-Fernando-Molina** [comment]
Hi Gabriel, thanks for trying out the app. 

Instead of trying to figure out the specific error you got, I would rather recommend you to install the latest un-released version which already have tons of bug fixes. This latest version is about to be released very soon.  Currently is available at this telegram group for testers:

https://t.me/joinchat/H62z4k3TdiMTn7aMWbqloA

Just scroll up a bit and you will find where I posted version 0 0 3 14.zip and the Workspace I was using to test myself intermediately above it.

Regarding the build, yes, it is true is not described anywhere yet. The build process as of today is very primitive. It is just about zipping all the folder structure of different projects / repos removing not needed files and folders to save space and to have a clean structure only with needed .js .json .env files and that's it.

Once you unzip the code you get all the needed projects in a folder structure exactly as it is needed for all this to run. We have an .exe for users who installing node.js is a big deal, but others can do "node run" to run from source code. 

If you would like to debug or contribute to some specific module, you can clone it's repo into the same folder on the structure the unzipping left there and everything should continue working just fine. Once cloned you will get in most cases visual studio files with solutions already setup. That way you might run that module in debug mode while the rest of the APP is running through the unzipped code. From there you can make your commits and push them. 

If you would clone all the repos into their corresponding folders of this structure, you would end up having the same local development environment I have.  

Finally, there might be some tricks to debug specific modules, just ask me if you find any roadblock. 

@julian-molina you might find here some info for devs to add to your documentation

**Comment by julian-molina** [comment]
Hola @gabrielacosta...

If you do move to the latest unreleased version as @Luis-Fernando-Molina suggested, you may find useful the README in the develop branch of this repository: https://github.com/Superalgos/DesktopApp/blob/develop/README.md

It is WIP and incomplete, but refers to the unreleased version which introduces several important changes...

**Comment by gabrielacosta** [comment]
Hi Luis and Fernando, 

Thanks for the quick response. 

I will try the latest unreleased version and keep you posted about my findings. 

Kind regards, 

Gabriel
